### ISSUE TITLE
Rack Display

### ISSUE THREAD

**Issue by flaviagfigueiredo** [Self-Service-Campus/ssc-django#35]

**Comment by tomas99batista** [comment]
é preciso tambem meter o rack por ip e nao hostname

**Comment by tomas99batista** [comment]
agrupar por bastiao e de cima para baixo

**Comment by tomas99batista** [comment]
Hostname done mas bugs pq n aparecem todos. ver: 8c83830a3e088e783f5ae9dcf29727f5f1c1b792

**Comment by tomas99batista** [comment]
Status atual: ainda n da para clicar e ver as infos nem alternar entre switch

![image](https://user-images.githubusercontent.com/34144094/85173937-414d0480-b26c-11ea-8393-1491084359fd.png)
@flaviagfigueiredo

**Comment by tomas99batista** [comment]
Done. ty ty ty @flaviagfigueiredo  

See: 7c7087ab72b929c16ea4da6e698d28765754c8cb
